# Generated by Django 4.2.5 on 2023-09-08 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockWriting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "mock_writing",
            },
        ),
        migrations.CreateModel(
            name="MockWritingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="writing_questions"
                    ),
                ),
                ("tips", models.TextField()),
                (
                    "writing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing",
                        to="mock.mockwriting",
                    ),
                ),
            ],
            options={
                "db_table": "mock_writing_question",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MockWritingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_response",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "writing_question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_response",
                        to="mock.mockwritingquestion",
                    ),
                ),
            ],
            options={
                "db_table": "mock_writing_response",
            },
        ),
    ]
